In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
Importing library


SyntaxError: invalid syntax (3671925889.py, line 1)

In [2]:
import numpy as np # 1d array/vector

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3,)

In [8]:
a.ndim

1

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(b)

numpy.ndarray

In [12]:
b.shape

(2, 3)

In [13]:
b.ndim

2

In [20]:
c = np.array([[[1.2,2,3],
                [4,5,6],
                [7,8,9]]])


d = np.array ([[[1,2,3]
                ,[4,5,6],
                [7,8,9]],
               
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [29]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [28]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [31]:
a.size,b.size,c.size,d.size # size means how manyelements in array

(3, 6, 9, 18)

In [32]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes

(24, 48, 72, 144)

Array creation

In [40]:
array1 = np.array([1,2,3], dtype = "int")

In [41]:
array1

array([1, 2, 3])

In [43]:
 zeros = np.zeros((2,2), dtype = float)
    

In [44]:
zeros

array([[0., 0.],
       [0., 0.]])

In [47]:
ones = np.ones((3,3), dtype = "int")

In [48]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
full = np.full((2,3), 5)

In [50]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [51]:
identity = np.identity((3), dtype = "int")

In [52]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
eye = np.eye(3,3, 2)

In [58]:
eye

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
arange = np.arange(1,10,2)

In [61]:
arange

array([1, 3, 5, 7, 9])

In [73]:
linspace = np.linspace (1,10,14, dtype = "int")

In [74]:
linspace

array([ 1,  1,  2,  3,  3,  4,  5,  5,  6,  7,  7,  8,  9, 10])

In [75]:
linspace.size

14

In [77]:
empty = np.empty((1,5))

In [78]:
empty

array([[0. , 0.5, 1. , 1.5, 2. ]])

In [84]:
for i in range(5):
    empty[:,i]=i
    empty
 


In [85]:
empty

array([[0., 1., 2., 3., 4.]])

# array indexing and slicing

#indexing

In [92]:
arr1 = np.array([1,2,3,4,5])
                
                 

In [93]:
print(arr1)

[1 2 3 4 5]


In [98]:
arr1[0]

1

In [99]:
arr1[3]

4

In [100]:
arr1[-1]

5

In [101]:
arr2 = np.random.randint(1,10, size =(3,3))

In [102]:
arr2

array([[5, 1, 1],
       [4, 1, 5],
       [8, 7, 4]])

In [103]:
arr2[0][0]

5

In [104]:
arr2[0][1]

1

In [105]:
arr2[2,2]

4

In [108]:
arr3= np.random.randint(1,10,size = (2,3,3))

In [109]:
arr3

array([[[2, 3, 4],
        [3, 1, 3],
        [3, 4, 8]],

       [[1, 5, 1],
        [5, 1, 9],
        [5, 9, 5]]])

In [110]:
arr3[0][1][1]

1

In [111]:
arr3[1][2][2]

5

In [112]:
arr3[1,1,1]

1

#slicing

In [113]:
print(arr1)

[1 2 3 4 5]


In [115]:
arr1[0:3]

array([1, 2, 3])

In [117]:
print(arr1[2:])

[3 4 5]


In [118]:
arr2

array([[5, 1, 1],
       [4, 1, 5],
       [8, 7, 4]])

In [119]:
arr2[0:2,0:2]

array([[5, 1],
       [4, 1]])

# manipulating array shape
1. Reshape
2.Resize
3.Plattern
4.Revel
5.Defining array shape

### Reshape

In [121]:

a = np.array([[1,2,3,],
              [3,4,5]])

In [122]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [123]:
a.shape

(2, 3)

In [127]:
a_reshaped = np.reshape(a,(3,2))

In [128]:
a_reshaped

array([[1, 2],
       [3, 3],
       [4, 5]])

In [129]:
a_reshaped.size

6

In [130]:
a_reshaped.shape

(3, 2)

In [135]:
a_reshaped2 = np.reshape(a,(3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

#### Resize

In [136]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [137]:
a_resized = np.resize(a,(3,3))

In [138]:
a_resized

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3]])

### Ravel

In [154]:
a = np.random.randint(1,10,(2,3))

In [155]:
a

array([[6, 5, 7],
       [7, 7, 1]])

In [156]:
a_raveled = np.ravel(a)

In [157]:
a_raveled

array([6, 5, 7, 7, 7, 1])

In [166]:
a_raveled[0] = 0

In [167]:
a_raveled

array([0, 5, 7, 7, 7, 1])

In [168]:
a

array([[0, 5, 7],
       [7, 7, 1]])

In [169]:
a_raveled.shape

(6,)

##### Flaten

In [170]:
a

array([[0, 5, 7],
       [7, 7, 1]])

In [172]:
a_flattened = a.flatten()# return a copy of the orginal array even u change in element


In [173]:
a_flattened

array([0, 5, 7, 7, 7, 1])

In [174]:
a_flattened[0] = 100

In [175]:
a_flattened

array([100,   5,   7,   7,   7,   1])

In [176]:
a

array([[0, 5, 7],
       [7, 7, 1]])

### defining array shape

In [177]:
a

array([[0, 5, 7],
       [7, 7, 1]])

In [178]:
a.shape = (3,2)

In [179]:
a

array([[0, 5],
       [7, 7],
       [7, 1]])

In [181]:
a = np.arange(1,10).reshape(3,3)

In [182]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
b = 2*a

In [186]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [189]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

### verticle

In [193]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [194]:
np.row_stack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [200]:
x = np.linspace(0, 2, 10)

In [201]:
x

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [204]:
x = np.linspace(1, 2*np.pi,num = 100)

In [205]:
x

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
l=[1,2,"tri",6,6.7]
print(l)

[1, 2, 'tri', 6, 6.7]


In [7]:
 arr=np.array(l)
 print(arr)

['1' '2' 'tri' '6' '6.7']


In [8]:
type(arr)

numpy.ndarray

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [15]:
np.arange(-10,20)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [16]:
np.arange(10,10)

array([], dtype=int64)

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
# 10- starting from 30- end point 5 - step count
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
np.arange(3,19,3)

array([ 3,  6,  9, 12, 15, 18])

In [21]:
np.arange(3,19,6)

array([ 3,  9, 15])

In [23]:
# zeros function wit row and column specifiy
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# ones function wit row and column specifiy
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
#wrong with tws or threes functon
np.Twos((6,6))

AttributeError: module 'numpy' has no attribute 'Twos'

In [30]:
#without np also possible to operate
from numpy import*
arange(9)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
#without np also possible to operate
from numpy import*
arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
from numpy import*
zeros(4)

array([0., 0., 0., 0.])

In [40]:
#randint function
np.random.randint(10,30)

24

In [41]:
#randint function
np.random.randint(10,30,8)

array([22, 22, 12, 13, 22, 18, 25, 10])

In [42]:
np.random.randint(1) 

0

In [43]:
#generate the elements 10 to 70 with 5*5 matrix
np.random.randint(10,270,(5,5)) 

array([[253,  33, 185, 242,  18],
       [ 24,  61, 260, 237, 225],
       [ 70, 248, 194,  82, 210],
       [259, 187,  76, 207, 212],
       [123,  42,  48, 151, 253]])

In [46]:
np.random.randint(50,200,(8,9))

array([[181, 170,  77, 124, 192, 134, 143, 151, 137],
       [141,  88, 127,  79, 100, 125, 159,  91, 140],
       [140, 111, 116, 175,  98, 177, 100, 167, 154],
       [185, 108,  82, 165,  75, 178, 140,  57, 109],
       [170,  69,  77, 163, 175, 127,  72, 157, 182],
       [148, 197, 124,  73, 111, 172,  85, 140, 139],
       [182,  73, 161, 101, 102,  94,  75, 123,  55],
       [ 52,  56, 181, 185, 162,  86, 115, 169,  88]])

In [73]:
#arithmatic function
a = np.random.randint(10,20,6)
a

array([18, 16, 19, 15, 13, 17])

In [76]:
arr=a

In [77]:
arr.min()

13

In [78]:
arr.max()

19

In [79]:
arr.mean()

16.333333333333332

In [80]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [56]:
a= arr
a.median


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [81]:
# but you can find median this way
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [82]:
arr

array([18, 16, 19, 15, 13, 17])

In [83]:
arr.reshape(2,3)

array([[18, 16, 19],
       [15, 13, 17]])

In [84]:
arr.reshape(3,2)

array([[18, 16],
       [19, 15],
       [13, 17]])

In [85]:
arr.reshape(1,6)

array([[18, 16, 19, 15, 13, 17]])

In [86]:
arr.reshape(6,1)

array([[18],
       [16],
       [19],
       [15],
       [13],
       [17]])

In [87]:
# but not possible without the total size 6
arr.shape(1,4)

TypeError: 'tuple' object is not callable

In [109]:
#indexing
met = np.arange(0,50).reshape(10,5)
met

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [94]:
met.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
#slicing
met[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [103]:
#deletes row 
met[:,col] 

NameError: name 'col' is not defined

In [104]:
met[row,:]

NameError: name 'row' is not defined

In [105]:
col = 1

# delete the column using the delete() function
met = np.delete(met, col, axis=1)

# print the updated array
print(met)

[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]
 [20 22 23 24]
 [25 27 28 29]
 [30 32 33 34]
 [35 37 38 39]
 [40 42 43 44]
 [45 47 48 49]]


In [106]:
row = 3
# delete the column using the delete() function
met = np.delete(met, row, axis=0)

# print the updated array
print(met)

[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [20 22 23 24]
 [25 27 28 29]
 [30 32 33 34]
 [35 37 38 39]
 [40 42 43 44]
 [45 47 48 49]]


In [144]:
#want to find the column which i defined
met[:,col]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [145]:
#want to find the row which i defined
met[row,:]

array([15, 16, 17, 18, 19])

In [107]:
met[1:4,1:3,] 

array([[ 7,  8],
       [12, 13],
       [22, 23]])

In [146]:
#Reversing
met[::-1]

array([[45, 46, 47, 48, 49],
       [40, 41, 42, 43, 44],
       [35, 36, 37, 38, 39],
       [30, 31, 32, 33, 34],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [147]:
met[2:3,2:3]

array([[12]])

In [110]:
#Masking or Filtering
met

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [111]:
met>30

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [112]:
met<25

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [115]:
a=met[met>35]
a

array([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [116]:
a=met[met<25]
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [117]:
#tuple explöring
# Creating a tuple with 3 elements
tuple1 = (1, 2, 3,5,6)
print(tuple1)


(1, 2, 3, 5, 6)


In [120]:
print(tuple1[2])
print(tuple1[3])


3
5


In [122]:
#Concatenating two tuples:
tuple2 = (5,7,7.9)
tuple_com= tuple1 + tuple2
print(tuple_com)

(1, 2, 3, 5, 6, 5, 7, 7.9)


In [123]:

#slicing allow
tuple_com[1:5]

(2, 3, 5, 6)

In [126]:
# converting list to tuple
list1= [5,5,8,6,9]
tuple_3 = tuple(list1)
print(tuple_3)



(5, 5, 8, 6, 9)


In [127]:
#unpacking tuple
a,b,c,d,e= tuple_3
print(a)
print(b)
print(c)

5
5
8


In [128]:
tuple_3

(5, 5, 8, 6, 9)

In [129]:
#append, add and remove not aplicable in tuple
tuple_3.append(50)

AttributeError: 'tuple' object has no attribute 'append'

In [130]:
tuple_3.add(30)

AttributeError: 'tuple' object has no attribute 'add'

In [131]:
tuple_3.remove(6)

AttributeError: 'tuple' object has no attribute 'remove'

In [133]:
#but you can duplicate your tuple inside  tuple
t_4= tuple_3*3
print(t_4)

(5, 5, 8, 6, 9, 5, 5, 8, 6, 9, 5, 5, 8, 6, 9)


In [134]:
# you can not replace inside tuple
t_4[2]= 50

TypeError: 'tuple' object does not support item assignment

In [135]:
#you can declare list in tuple also tuple in tuple
tt=(2,3,4,[5,6,7],6,8)
tt

(2, 3, 4, [5, 6, 7], 6, 8)

In [136]:
tt1=(5,6,7,(7,8),6)
tt1

(5, 6, 7, (7, 8), 6)

In [137]:
#making tuple
colors = "red", "green", "blue"
colors


('red', 'green', 'blue')

In [139]:
#Reversing,The syntax "[::-1]" means "start at the end of the sequence, move backward by one step, and include all elements
rev=colors[::-1]
rev

('blue', 'green', 'red')

In [140]:
#The syntax "[::-2]" in Python means "start at the end of the sequence, move backward by two steps, and include all elements until the beginning of the sequence".
rev=colors[::-2]
rev

('blue', 'red')

In [149]:
rev.Del()

AttributeError: 'tuple' object has no attribute 'Del'